### ISSUE TITLE
[BUG] Machine gun disapears after placing it 

### ISSUE THREAD

**Issue by PolandSpaceCamp** [Pabilo8/ImmersiveIntelligence#120] opened 2021-05-08 20:52 UTC
**Describe the bug**
I am in a survival server and I made the Machine gun three times. All three times after placing the machine gun the gun disappears. The first time It just disappeared when moving around it after placing it. The second time I used my sword to hit it and it disappeared. The third time I crouched at right clicked it and it disappeared. I then went into a single player creative and using the same mods in the server it would drop whenever I tried to pick it up. 

**Expected behavior**
A clear description of what you expected to happen.
I expected the machine gun to drop after picking it up but instead it destroyed itself 

**Screenshots or GIFs**
Add screenshots of animated GIFs (even better) of the problem (if it is a visual glitch).
N/A 

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ).
N/A (No logs in the server) 

**Environment**
 - OS: Windows 
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: immersiveintelligence-1.12.2-0.1.1.jar
 - Immersive Engineering version: ImmersiveEngineering-0.12-98.jar
 
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
CraftTweaker
Pollution of the Realms
Advanced Chimneys
AppleCore
AppleSkin
Applied Energistics 2
AutoRegLib
BiblioCraft
Chameleon
Cooking for Blockheads
ForgeEndertech
GraveStone Mod
Hwyla

Immersive Engineering
Immersive Intelligence
Immersive Petroleum
Immersive Posts

Iron Chests
JourneyMap
Just Enough Items (JEI)
Just Enough Resources (JER)
Mantle
Mekanism
Mekanism Generators
Mekanism Tools
More Overlays
MrCrayfish's Furniture Mod
OpenBlocks
OpenModsLib
Pam's HarvestCraft
Realistic Torches
Reborn Core
Roguelike Dungeons
Scape and Run: Parasites
Spice of Life: Carrot Edition
Steve's Carts Reborn
Storage Drawers
Tinkers Construct
VeinMiner
ViesCraft - Airships!
Wawla - What Are We Looking At
YUNG's Better Caves (Forge)
YUNG's Better Mineshafts (Forge)

**Comment by Pabilo8** [comment] 2022-01-05 12:07
The issue is fixed in the latest version - 0.2.1.

**Closed by Pabilo8** 2022-01-05 12:07 UTC
Labels: bug
