### ISSUE TITLE
[BUG] Closing Engineers Manual closes connection to server

### ISSUE THREAD

**Issue by Kerzenmacher** [Pabilo8/ImmersiveIntelligence#164] opened 2022-03-02 00:58 UTC
If I try to close the Engineers Manual by pressing escape, my connection to the server is closed, stating "A fatal error has occurred, this connection is terminated" An error is logged on the server-side, but nothing is logged on client-side.

Open the manual then press escape.
Only reproduceable on multiplayer.

Expected the book to close normally.

Serverside log [ I copied out the relevant part, the entire log was 50k lines.. ]
[Server log.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/8165694/Server.log.txt)

**Environment**
 - 1.12.2 Forge Server
 - Forge version 14.23.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
 -Full modlist:
   [✔️] ActuallyAdditions-1.12.2-r152
  [✔️] ae2stuff-0.7.0.4-mc1.12.2
  [✔️] AE2WTLib-1.12.2-1.0.34
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] baubley-heart-canisters-1.12.2-2.0.3
  [✔️] bdlib-1.14.3.12-mc1.12.2
  [✔️] BetterBuildersWands-1.12-0.11.1.245+69d0d70
  [✔️] bettercaves-1.12.2-2.0.4
  [✔️] BetterFps-1.4.8
  [✔️] BetterMineshaftsForge-1.12.2-2.2.1
  [✔️] BiblioCraft[v2.4.6][MC1.12.2]
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] Botania r1.10-364.4
  [✔️] BrandonsCore-1.12.2-2.4.20.162-universal
  [✔️] buildcraft-all-7.99.24.8
  [✔️] cc-tweaked-1.12.2-1.89.2
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChickenChunks-1.12.2-2.4.2.74-universal
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] chiselsandbits-14.33
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] CompactSolars-1.12.2-5.0.18.341-universal
  [✔️] Controlling-3.0.10
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] CraftTweaker2-1.12-4.1.20.674
  [✔️] crimsonrevelations-0.8
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] DarkUtils-1.12.2-1.8.230
  [✔️] Decocraft-2.6.3.7_1.12.2
  [✔️] deepresonance-1.12-1.8.0
  [✔️] DenseMetals-1.12.2-2.0.0.30
  [✔️] Draconic-Evolution-1.12.2-2.3.28.354-universal
  [✔️] ElecCore-1.12.2-1.9.453
  [✔️] ElevatorMod-1.12.2-1.3.14
  [✔️] EmbersRekindled-1.18
  [✔️] EnderCore-1.12.2-0.5.76
  [✔️] endercrop-1.12.2-1.6.0
  [✔️] EnderIO-1.12.2-5.3.70
  [✔️] EnderIO-conduits-mekanism-1.12.2-5.3.70
  [✔️] EnderStorage-1.12.2-2.4.6.137-universal
  [✔️] endertanks-1.12.0-1.6.8
  [✔️] EnderTweaker-1.12.2-1.2.3
  [✔️] engineers_doors-1.12.2-0.9.1
  [✔️] engineersdecor-1.12.2-1.1.4
  [✔️] Exchangers-1.12.2-2.10.1
  [✔️] ExtraCells-1.12.2-2.6.7
  [✔️] extrautils2-1.12-1.9.9
  [✔️] ExtremeReactors-1.12.2-0.4.5.68
  [✔️] FastLeafDecay-v14
  [✔️] foamfix-0.10.14-1.12.2
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] FTBLib-5.4.7.2
  [✔️] FTBUtilities-5.4.1.131
  [✔️] furniture-6.3.1-1.12.2
  [✔️] GalacticraftCore-1.12.2-4.0.2.280
  [✔️] Galacticraft-Planets-1.12.2-4.0.2.280
  [✔️] GunpowderLib-1.12.2-1.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] ic2-tweaker-0.2.0
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] ImmersiveCables-1.12.2-1.3.2
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersiveintelligence-0.2.1
  [✔️] immersivepetroleum-1.12.2-1.1.10
  [✔️] immersivetweaker-0.1
  [✔️] industrialcraft-2-2.8.170-ex112
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] IntegrationForegoing-1.12.2-1.11
  [✔️] InventoryTweaks-1.63
  [✔️] IronBackpacks-1.12.2-3.0.8-12
  [✔️] ironchest-1.12.2-7.0.72.847
  [✔️] jei_1.12.2-4.16.1.301
  [✔️] jeiintegration_1.12.2-1.6.0
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] JustEnoughEnergistics-1.12.2-1.0.8
  [✔️] JustEnoughPetroleum-0.1
  [✔️] JustEnoughResources-1.12.2-0.9.2.60
  [✔️] logisticspipes-0.10.3.114
  [✔️] malisiscore-1.12.2-6.5.1
  [✔️] malisisdoors-1.12.2-7.3.0
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] mcjtylib-1.12-3.5.4
  [✔️] MCTImmersiveTechnology-1.12.2-1.9.100
  [✔️] Mekanism-1.12.2-9.8.3.390
  [✔️] MekanismGenerators-1.12.2-9.8.3.390
  [✔️] MekanismTools-1.12.2-9.8.3.390
  [✔️] mekores-2.0.13
  [✔️] MicdoodleCore-1.12.2-4.0.2.280
  [✔️] MineTweakerRecipeMaker-1.12.2-1.2.2.30
  [✔️] MJRLegendsLib-1.12.2-1.2.1
  [✔️] MmmMmmMmmMmm-1.12-1.14
  [✔️] moartinkers-0.6.0
  [✔️] MobGrindingUtils-0.3.13
  [✔️] modtweaker-4.0.20.5
  [✔️] ModularPowersuits-1.12.2-1.0.46
  [✔️] Morph-o-Tool-1.2-21
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] MTLib-3.0.7
  [✔️] Netherending-Ores-1.12.2-1.4.2
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] Numina-1.12.2-1.0.38
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OptiFine_1.12.2_HD_U_E3
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Patchouli-1.0-23.6
  [✔️] pneumaticcraft-repressurized-1.12.2-0.11.15-398
  [✔️] PortalGun-1.12.2-7.1.0
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-compat
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] PTRLib-1.0.5
  [✔️] Quark-r1.6-179
  [✔️] railcraft-12.0.0
  [✔️] rangedpumps-0.5
  [✔️] RedstoneArsenal-1.12.2-2.6.6.1-universal
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal
  [✔️] RedstoneRepository-1.12.2-2.0.0
  [✔️] RoguelikeDungeonsFnarEdition-1.12.2-2.4.1
  [✔️] rsgauges-1.12.2-1.2.5
  [✔️] rustic-1.1.7
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] SimplyJetpacks2-1.12.2-2.2.20.0
  [✔️] spark-forge
  [✔️] SteamWorld 1.12.2-0.4.0.2
  [✔️] StorageDrawers-1.12.2-5.4.2
  [✔️] tc6aspects4jei-0.0.2a
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] tesla-core-lib-1.12.2-1.0.18
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicAugmentation-1.12.2-2.1.5
  [✔️] thaumicenergistics-2.2.4
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] thaumictinkerer-1.12.2-5.0-620a0c5
  [✔️] TheBetweenlands-3.8.1-universal
  [✔️] ThermalCultivation-1.12.2-0.3.6.1-universal
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal
  [✔️] ThermalExpansion-1.12.2-5.5.7.1-universal
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal
  [✔️] ThermalTinkering-1.12.2-2.0.1
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] tinkersjei-1.2
  [✔️] TMechworks-1.12.2-1.0.0
  [✔️] twilightforest-1.12.2-3.11.1021-universal
  [✔️] UniDict-1.12.2-3.0.10
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] WanionLib-1.12.2-2.9
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] WirelessCraftingTerminal-1.12.2-3.12.97
  [✔️] WR-CBE-1.12.2-2.3.2.33-universal
  [✔️] YABBA-1.1.2.54
  [✔️] zerocore-1.12.2-0.1.2.9

**Comment by Pabilo8** [comment] 2022-03-04 12:16
Duplicate of #148 , will be fixed in next push

**Closed by Pabilo8** 2022-03-04 12:16 UTC
