### ISSUE TITLE
smg casings are uncraftable [BUG]

### ISSUE THREAD

**Issue by TachankaTheKity** [Pabilo8/ImmersiveIntelligence#146] opened 2022-01-14 01:50 UTC
smg casings are uncraftable, the recipe instead makes artillery shell casings

To Reproduce
1. try to make smg casing
2. get artillery casing

Expected behavior
1. try to make smg casing
2. get smg casing

![image](https://user-images.githubusercontent.com/97713533/149436759-6ed871ac-f4bd-4f19-8b9e-95a8f56a3dee.png)

Logs
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/7867069/latest.log)

Environment
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
other mods
Jei 4.16.1.302
Jei integration 1.6.0 (specifically tested it without other mods)

**Comment by Pabilo8** [comment] 2022-01-16 11:47
Duplicate of #134, fixed in 87f2279

**Closed by Pabilo8** 2022-01-16 11:47 UTC
