### ISSUE TITLE
[BUG] Crash when starting Minecraft in 0.2.1

### ISSUE THREAD

**Issue by JustDesoroxxx** [Pabilo8/ImmersiveIntelligence#201] opened 2022-07-19 17:03 UTC
**Describe the bug**
The game crash with the latest version at launch.

**To Reproduce**
1. Use latest version
2. Launch the game
3. Wait a bit
4. And crash

**Expected behavior**
Game launching without crashing.

**Logs**
https://i-like.cat/ImmersiveIntelligenceCrashReport

**Environment**
 - OS: Windows 11 Education Build 22622.290 (Dev Channel)
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2860
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
 
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
Just look in the crash report there is the list of all the mods at the bottom with their current states.

**Comment by Pabilo8** [comment] 2022-08-12 13:52
Can't view the logs, the link is broken.
It might be related to you having an old config file, like in #209 . If that's the case, remove the config file and it should work.

Also, please close the issue if the problem is fixed.

**Closed by Pabilo8** 2022-08-12 13:52 UTC
Labels: Needs Investigation

**Comment by JustDesoroxxx** [comment] 2022-08-12 15:32
> Can't view the logs, the link is broken. It might be related to you having an old config file, like in #209 . If that's the case, remove the config file and it should work.
> 
> Also, please close the issue if the problem is fixed.

Sorry for broken link, old config is a good guess will try it asap and if it is still crashing the game will send a crash report without a broken link this time!

**Comment by JustDesoroxxx** [comment] 2022-08-12 16:54
Okay so after testing it seems that the crash I was having consistently is now gone after deleting the config.

Thanks a lot!
