### ISSUE TITLE
[BUG] minecraft is crashing with terrafirmacraft

### ISSUE THREAD

**Issue by ZoniIC645** [Pabilo8/ImmersiveIntelligence#28] opened 2020-04-28 04:57 UTC
**Describe the bug**
I tried to run minecraft with TFC and Game was crashed

**To Reproduce**
1.Run minecraft

**Expected behavior**
game is crashing

**Logs**
(https://github.com/Pabilo8/ImmersiveIntelligence/files/4543396/crash-2020-04-28_12.12.53-client.txt)

**Environment**
 - OS:window 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 1.12.2-0.1.0
 - Immersive Engineering version: 0.12-92
 - Terrafirmacraft version : 1.12.2-0.30.3.124

**Comment by Pabilo8** [comment] 2020-04-28 06:43
Duplicate of #26, will be fixed in the next release.

**Closed by Pabilo8** 2020-04-28 06:43 UTC
